apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.17.255.10
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dnstcp
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dnsudp