apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    tier: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: paymentservice
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurger: 0
  template:
    metadata:
      labels:
        app: paymentservice
        tier: paymentservice
    spec:
      containers:
        - name: server
          image: pavel12513/paymentservice:v0.0.1
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"