apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: lesson_1
spec:
  containers:
    - name: web
      image: pavel12513/pavel12513_outus_lesson1:v01
      volumeMounts:
        - name: app
          mountPath: /app
      livenessProbe:
        tcpSocket:
          port: 8000
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8000
  initContainers:
    - name: init
      image: busybox:stable
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: { }
